class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start5'
        self.MirrorCommand = 'mirror5'
        self.UnzipMirrorCommand = 'unzipmirror5'
        self.TarMirrorCommand = 'tarmirror5'
        self.ZipMirrorCommand = 'zipmirror5'
        self.CancelMirror = 'cancel5'
        self.CancelAllCommand = 'cancelall5'
        self.ListCommand = 'list5'
        self.StatusCommand = 'status5'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping5'
        self.RestartCommand = 'restart5'
        self.StatsCommand = 'stats5'
        self.HelpCommand = 'help5'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'clone5'
        self.CountCommand = 'count'
        self.WatchCommand = 'watch5'
        self.TarWatchCommand = 'tarwatch5'
        self.ZipWatchCommand = 'zipwatch5'
        self.QbMirrorCommand = 'qbmirror5'
        self.QbUnzipMirrorCommand = 'qbunzipmirror5'
        self.QbTarMirrorCommand = 'qbtarmirror5'
        self.QbZipMirrorCommand = 'qbzipmirror5'
        self.DeleteCommand = 'del5'
        self.ShellCommand = 'shell'
        self.ExecHelpCommand = 'exechelp'
        self.TsHelpCommand = 'tshelp5'

BotCommands = _BotCommands()
